<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { APP_VERSION, dataLocalISO, ehMenor, taxaPresencaRegistros, validarDadosBackup } from './domain'

type StatusJovem = 'Ativo' | 'Atenção' | 'Acompanhamento'
type TipoJovem = 'Participante' | 'Visitante' | 'Liderança'
type GrupoTipo = 'Equipe' | 'Grupo' | 'Ministério'
type PerfilUsuario = 'Administrador Master' | 'Coordenação' | 'Liderança' | 'Comunicação' | 'Financeiro' | 'Consulta'
type Jovem = { id:string; nome:string; telefone:string; email?:string; nascimento:string; status:StatusJovem; equipe:string; menor:boolean; tipo?:TipoJovem; responsavel?:string; telefoneResponsavel?:string }
type Evento = { id:string; titulo:string; data:string; local:string; inscritos:number }
type Presenca = { jovemId:string; data:string; presente:boolean }
type Grupo = { id:string; nome:string; tipo:GrupoTipo; lider:string; ativo:boolean }
type Acompanhamento = { id:string; jovemId:string; motivo:string; responsavel:string; prazo:string; status:'Pendente'|'Concluído'; criadoEm:string }
type Usuario = { id:string; nome:string; perfil:PerfilUsuario; ativo:boolean }
type Configuracao = { nomeGrupo:string; cidade:string; radarAmarelo:number; radarVermelho:number }
type Estado = { jovens:Jovem[]; eventos:Evento[]; presencas:Presenca[]; grupos:Grupo[]; acompanhamentos:Acompanhamento[]; usuarios:Usuario[]; configuracao:Configuracao }
type Cofre = { schema:'sgj-vault'; version:1; appVersion:string; salt:string; iv:string; ciphertext:string }
type BackupSeguro = { schema:'sgj-backup'; version:1; appVersion:string; salt:string; iv:string; ciphertext:string }

const CHAVE_COFRE = 'sgj_secure_vault'
const CHAVES_LEGADAS = ['sgj_jovens','sgj_eventos','sgj_presencas','sgj_grupos','sgj_acompanhamentos','sgj_usuarios','sgj_config']
const hoje = dataLocalISO()
const nav = [['dashboard','Painel'],['jovens','Jovens'],['eventos','Eventos'],['presenca','Presença'],['grupos','Grupos e equipes'],['acompanhamento','Acompanhamento'],['relatorios','Relatórios'],['admin','Administração']] as const

function estadoVazio():Estado { return { jovens:[], eventos:[], presencas:[], grupos:[], acompanhamentos:[], usuarios:[], configuracao:{nomeGrupo:'Meu Grupo de Jovens',cidade:'',radarAmarelo:14,radarVermelho:30} } }
function parseLegado<T>(chave:string, fallback:T):T { try { const v=localStorage.getItem(chave); return v ? JSON.parse(v) as T : fallback } catch { return fallback } }
function estadoLegado():Estado { const vazio=estadoVazio(); return { jovens:parseLegado('sgj_jovens',vazio.jovens), eventos:parseLegado('sgj_eventos',vazio.eventos), presencas:parseLegado('sgj_presencas',vazio.presencas), grupos:parseLegado('sgj_grupos',vazio.grupos), acompanhamentos:parseLegado('sgj_acompanhamentos',vazio.acompanhamentos), usuarios:parseLegado('sgj_usuarios',vazio.usuarios), configuracao:parseLegado('sgj_config',vazio.configuracao) } }
function bytesBase64(bytes:Uint8Array){ let s=''; bytes.forEach(b=>s+=String.fromCharCode(b)); return btoa(s) }
function base64Bytes(valor:string){ const s=atob(valor); return Uint8Array.from(s,c=>c.charCodeAt(0)) }
async function derivarChave(senha:string,salt:Uint8Array){ const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(senha),'PBKDF2',false,['deriveKey']); return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']) }
async function criptografarJson(valor:unknown,chave:CryptoKey,salt:Uint8Array){ const iv=crypto.getRandomValues(new Uint8Array(12)); const dados=new TextEncoder().encode(JSON.stringify(valor)); const cifrado=await crypto.subtle.encrypt({name:'AES-GCM',iv},chave,dados); return {salt:bytesBase64(salt),iv:bytesBase64(iv),ciphertext:bytesBase64(new Uint8Array(cifrado))} }
async function descriptografarJson<T>(pacote:{iv:string;ciphertext:string},chave:CryptoKey):Promise<T>{ const claro=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64Bytes(pacote.iv)},chave,base64Bytes(pacote.ciphertext)); return JSON.parse(new TextDecoder().decode(claro)) as T }

const tela=ref('dashboard'), busca=ref(''), aviso=ref(''), senhaAcesso=ref(''), senhaBackup=ref(''), bloqueado=ref(true), temCofre=ref(Boolean(localStorage.getItem(CHAVE_COFRE))), salvando=ref(false)
const jovens=ref<Jovem[]>([]), eventos=ref<Evento[]>([]), presencas=ref<Presenca[]>([]), grupos=ref<Grupo[]>([]), acompanhamentos=ref<Acompanhamento[]>([]), usuarios=ref<Usuario[]>([]), configuracao=ref<Configuracao>(estadoVazio().configuracao)
let chaveSessao:CryptoKey|null=null, saltSessao:Uint8Array|null=null, filaPersistencia=Promise.resolve()

function aplicarEstado(e:Estado){ jovens.value=e.jovens; eventos.value=e.eventos; presencas.value=e.presencas; grupos.value=e.grupos; acompanhamentos.value=e.acompanhamentos; usuarios.value=e.usuarios; configuracao.value=e.configuracao }
function estadoAtual():Estado { return {jovens:jovens.value,eventos:eventos.value,presencas:presencas.value,grupos:grupos.value,acompanhamentos:acompanhamentos.value,usuarios:usuarios.value,configuracao:configuracao.value} }
function mostrarAviso(texto:string){ aviso.value=texto; window.setTimeout(()=>{if(aviso.value===texto) aviso.value=''},3200) }
async function persistir(){ if(!chaveSessao||!saltSessao||bloqueado.value)return; salvando.value=true; try { const pacote=await criptografarJson(estadoAtual(),chaveSessao,saltSessao); const cofre:Cofre={schema:'sgj-vault',version:1,appVersion:APP_VERSION,...pacote}; localStorage.setItem(CHAVE_COFRE,JSON.stringify(cofre)) } finally { salvando.value=false } }
function agendarPersistencia(){ if(!chaveSessao||bloqueado.value)return; filaPersistencia=filaPersistencia.then(persistir).catch(()=>mostrarAviso('Falha ao salvar os dados locais.')) }
;[jovens,eventos,presencas,grupos,acompanhamentos,usuarios,configuracao].forEach(r=>watch(r,agendarPersistencia,{deep:true}))

async function acessar(){
  if(senhaAcesso.value.length<8){ mostrarAviso('Use uma senha local com pelo menos 8 caracteres.'); return }
  try{
    const bruto=localStorage.getItem(CHAVE_COFRE)
    if(bruto){ const cofre=JSON.parse(bruto) as Cofre; if(cofre.schema!=='sgj-vault'||cofre.version!==1) throw new Error('cofre'); saltSessao=base64Bytes(cofre.salt); chaveSessao=await derivarChave(senhaAcesso.value,saltSessao); const estado=await descriptografarJson<Estado>(cofre,chaveSessao); if(!validarDadosBackup(estado)) throw new Error('estado'); aplicarEstado(estado) }
    else { saltSessao=crypto.getRandomValues(new Uint8Array(16)); chaveSessao=await derivarChave(senhaAcesso.value,saltSessao); aplicarEstado(estadoLegado()); bloqueado.value=false; await persistir(); CHAVES_LEGADAS.forEach(k=>localStorage.removeItem(k)); temCofre.value=true; senhaAcesso.value=''; mostrarAviso('Cofre local criado e dados legados protegidos.'); return }
    bloqueado.value=false; senhaAcesso.value=''; mostrarAviso('Acesso local desbloqueado.')
  }catch{ chaveSessao=null; saltSessao=null; mostrarAviso('Senha incorreta ou cofre local inválido.') }
}
function bloquear(){ chaveSessao=null; saltSessao=null; bloqueado.value=true; senhaAcesso.value=''; tela.value='dashboard' }

const filtrados=computed(()=>jovens.value.filter(j=>[j.nome,j.telefone,j.email,j.equipe].some(v=>(v||'').toLowerCase().includes(busca.value.toLowerCase()))))
const ativos=computed(()=>jovens.value.filter(j=>j.status==='Ativo').length), alertas=computed(()=>jovens.value.filter(j=>j.status!=='Ativo').length), menores=computed(()=>jovens.value.filter(j=>j.menor).length), visitantes=computed(()=>jovens.value.filter(j=>j.tipo==='Visitante').length)
const presentesHoje=computed(()=>presencas.value.filter(p=>p.data===hoje&&p.presente).length), pendentes=computed(()=>acompanhamentos.value.filter(a=>a.status==='Pendente').length), diasComPresenca=computed(()=>new Set(presencas.value.map(p=>p.data)).size), taxaPresenca=computed(()=>taxaPresencaRegistros(presencas.value))
const aniversariantesMes=computed(()=>{const mes=new Date().getMonth()+1;return jovens.value.filter(j=>j.nascimento&&Number(j.nascimento.slice(5,7))===mes)})
const distribuicaoEquipes=computed(()=>grupos.value.filter(g=>g.ativo).map(g=>({...g,membros:jovens.value.filter(j=>j.equipe===g.nome).length})))
const novo=ref({nome:'',telefone:'',email:'',nascimento:'',equipe:'',tipo:'Participante' as TipoJovem,responsavel:'',telefoneResponsavel:''}), novoEvento=ref({titulo:'',data:'',local:''}), novoGrupo=ref({nome:'',tipo:'Equipe' as GrupoTipo,lider:''}), novoAcompanhamento=ref({jovemId:'',motivo:'',responsavel:'',prazo:''}), novoUsuario=ref({nome:'',perfil:'Liderança' as PerfilUsuario})
const novoMenor=computed(()=>novo.value.nascimento?ehMenor(novo.value.nascimento,hoje):false)

function adicionarJovem(){ if(!novo.value.nome.trim()){mostrarAviso('Informe o nome.');return} const menor=novoMenor.value; if(menor&&(!novo.value.responsavel.trim()||!novo.value.telefoneResponsavel.trim())){mostrarAviso('Para menor de idade, informe responsável e telefone.');return} jovens.value.unshift({id:crypto.randomUUID(),nome:novo.value.nome.trim(),telefone:novo.value.telefone,email:novo.value.email,nascimento:novo.value.nascimento,equipe:novo.value.equipe,menor,tipo:novo.value.tipo,responsavel:menor?novo.value.responsavel:'',telefoneResponsavel:menor?novo.value.telefoneResponsavel:'',status:'Ativo'}); novo.value={nome:'',telefone:'',email:'',nascimento:'',equipe:'',tipo:'Participante',responsavel:'',telefoneResponsavel:''}; mostrarAviso('Jovem cadastrado.') }
function adicionarEvento(){if(!novoEvento.value.titulo.trim()||!novoEvento.value.data){mostrarAviso('Informe nome e data do evento.');return} eventos.value.unshift({id:crypto.randomUUID(),titulo:novoEvento.value.titulo.trim(),data:novoEvento.value.data,local:novoEvento.value.local,inscritos:0});novoEvento.value={titulo:'',data:'',local:''};mostrarAviso('Evento criado.')}
function alterarInscritos(id:string,delta:number){const e=eventos.value.find(x=>x.id===id);if(e)e.inscritos=Math.max(0,e.inscritos+delta)}
function adicionarGrupo(){if(!novoGrupo.value.nome.trim())return;grupos.value.push({id:crypto.randomUUID(),nome:novoGrupo.value.nome.trim(),tipo:novoGrupo.value.tipo,lider:novoGrupo.value.lider,ativo:true});novoGrupo.value={nome:'',tipo:'Equipe',lider:''};mostrarAviso('Grupo criado.')}
function desativarGrupo(id:string){const g=grupos.value.find(x=>x.id===id);if(g){g.ativo=false;mostrarAviso('Grupo desativado.')}}
function adicionarAcompanhamento(){if(!novoAcompanhamento.value.jovemId||!novoAcompanhamento.value.motivo.trim())return;acompanhamentos.value.unshift({id:crypto.randomUUID(),jovemId:novoAcompanhamento.value.jovemId,motivo:novoAcompanhamento.value.motivo.trim(),responsavel:novoAcompanhamento.value.responsavel,prazo:novoAcompanhamento.value.prazo,status:'Pendente',criadoEm:hoje});const j=jovens.value.find(x=>x.id===novoAcompanhamento.value.jovemId);if(j)j.status='Acompanhamento';novoAcompanhamento.value={jovemId:'',motivo:'',responsavel:'',prazo:''};mostrarAviso('Acompanhamento registrado.')}
function concluirAcompanhamento(id:string){const a=acompanhamentos.value.find(x=>x.id===id);if(a){a.status='Concluído';mostrarAviso('Acompanhamento concluído.')}}
function adicionarUsuario(){if(!novoUsuario.value.nome.trim())return;usuarios.value.push({id:crypto.randomUUID(),nome:novoUsuario.value.nome.trim(),perfil:novoUsuario.value.perfil,ativo:true});novoUsuario.value={nome:'',perfil:'Liderança'};mostrarAviso('Perfil local adicionado.')}
function nomeJovem(id:string){return jovens.value.find(j=>j.id===id)?.nome||'Jovem não localizado'}
function presente(id:string){return presencas.value.some(p=>p.jovemId===id&&p.data===hoje&&p.presente)}
function alternarPresenca(id:string){const idx=presencas.value.findIndex(p=>p.jovemId===id&&p.data===hoje);if(idx>=0)presencas.value[idx].presente=!presencas.value[idx].presente;else presencas.value.push({jovemId:id,data:hoje,presente:true})}
function marcarTodosPresentes(){jovens.value.forEach(j=>{const idx=presencas.value.findIndex(p=>p.jovemId===j.id&&p.data===hoje);if(idx>=0)presencas.value[idx].presente=true;else presencas.value.push({jovemId:j.id,data:hoje,presente:true})});mostrarAviso('Todos foram marcados como presentes.')}
function recalcularRadar(){const base=new Date(`${hoje}T12:00:00`).getTime();jovens.value.forEach(j=>{const datas=presencas.value.filter(p=>p.jovemId===j.id&&p.presente).map(p=>p.data).sort().reverse();if(!datas.length){j.status='Atenção';return}const dias=Math.floor((base-new Date(`${datas[0]}T12:00:00`).getTime())/86400000);j.status=dias>=configuracao.value.radarVermelho?'Acompanhamento':dias>=configuracao.value.radarAmarelo?'Atenção':'Ativo'});mostrarAviso('Radar recalculado.')}
function tituloTela(){return nav.find(n=>n[0]===tela.value)?.[1]||'SGJ'}
function statusClasse(s:StatusJovem){return s==='Ativo'?'green':s==='Atenção'?'yellow':'red'}
function iniciais(n:string){return n.split(' ').filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()}

async function exportarBackup(){if(senhaBackup.value.length<8){mostrarAviso('Defina uma senha de backup com pelo menos 8 caracteres.');return}const salt=crypto.getRandomValues(new Uint8Array(16));const chave=await derivarChave(senhaBackup.value,salt);const pacote=await criptografarJson(estadoAtual(),chave,salt);const backup:BackupSeguro={schema:'sgj-backup',version:1,appVersion:APP_VERSION,...pacote};const blob=new Blob([JSON.stringify(backup)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`sgj-backup-${hoje}.json`;a.click();URL.revokeObjectURL(url);mostrarAviso('Backup criptografado exportado.')}
async function importarBackup(event:Event){const input=event.target as HTMLInputElement,arquivo=input.files?.[0];if(!arquivo)return;try{const parsed=JSON.parse(await arquivo.text());let dados:unknown;if(parsed?.schema==='sgj-backup'){if(senhaBackup.value.length<8)throw new Error('senha');const salt=base64Bytes(parsed.salt);const chave=await derivarChave(senhaBackup.value,salt);dados=await descriptografarJson<Estado>(parsed,chave)}else dados=parsed?.dados??parsed;if(!validarDadosBackup(dados))throw new Error('estrutura');aplicarEstado(dados as Estado);await persistir();mostrarAviso('Backup importado e protegido no cofre local.')}catch{mostrarAviso('Backup inválido ou senha incorreta.')}finally{input.value=''}}
</script>

<template>
  <div v-if="bloqueado" class="shell" style="display:grid;place-items:center;grid-template-columns:1fr;padding:24px">
    <article class="panel" style="max-width:520px;width:100%">
      <span class="eyebrow">SGJ {{ APP_VERSION }}</span>
      <h1>{{ temCofre ? 'Desbloquear dados locais' : 'Criar cofre local protegido' }}</h1>
      <p class="muted">Os dados pessoais ficam criptografados neste dispositivo. A senha não é salva e será solicitada ao reabrir o aplicativo.</p>
      <form class="stack" @submit.prevent="acessar">
        <label>Senha local<input v-model="senhaAcesso" type="password" minlength="8" autocomplete="current-password" required></label>
        <button class="primary">{{ temCofre ? 'Desbloquear' : 'Criar acesso local' }}</button>
      </form>
      <div class="notice">A sincronização central e a autenticação multiusuário ainda não estão habilitadas. Não confunda este cofre local com login central.</div>
    </article>
    <div v-if="aviso" class="toast">{{ aviso }}</div>
  </div>

  <div v-else class="shell">
    <aside class="sidebar">
      <div class="brand"><div class="brandmark">SGJ</div><div><strong>Gestor de Jovens</strong><small>Web + PC · v{{ APP_VERSION }}</small></div></div>
      <nav><button v-for="item in nav" :key="item[0]" :class="{active:tela===item[0]}" @click="tela=item[0]"><span class="dot"></span>{{ item[1] }}</button></nav>
      <div class="sync"><span class="online"></span><div><strong>{{ salvando?'Salvando…':'Cofre local ativo' }}</strong><small>Dados criptografados no dispositivo</small></div></div>
    </aside>
    <main>
      <header><div><small>{{ configuracao.nomeGrupo }}<template v-if="configuracao.cidade"> · {{ configuracao.cidade }}</template></small><h1>{{ tituloTela() }}</h1></div><div class="user"><div class="avatar">SGJ</div><div><strong>Sessão local</strong><small>Protegida por senha</small></div><button class="link" @click="bloquear">Bloquear</button></div></header>
      <div v-if="aviso" class="toast">{{ aviso }}</div>

      <section v-if="tela==='dashboard'" class="page">
        <div class="hero"><div><span class="eyebrow">VISÃO GERAL</span><h2>Boa gestão começa por pessoas.</h2><p>Acompanhe integração, presença, equipes e quem precisa de atenção.</p></div><div class="heroactions"><button class="ghost" @click="recalcularRadar">Recalcular radar</button><button class="primary" @click="tela='jovens'">+ Cadastrar jovem</button></div></div>
        <div class="metrics"><article><small>Jovens cadastrados</small><strong>{{ jovens.length }}</strong><span>{{ visitantes }} visitantes</span></article><article><small>Ativos</small><strong>{{ ativos }}</strong><span class="good">Participação regular</span></article><article><small>Precisam de atenção</small><strong>{{ alertas }}</strong><span class="warn">{{ pendentes }} acompanhamentos pendentes</span></article><article><small>Presentes hoje</small><strong>{{ presentesHoje }}</strong><span>{{ jovens.length?Math.round(presentesHoje/jovens.length*100):0 }}% da base</span></article></div>
        <div class="grid2"><article class="panel"><div class="panelhead"><div><small>RADAR</small><h3>Acompanhamento</h3></div><span class="badge">{{ alertas }} alertas</span></div><div v-if="!alertas" class="quiet">Nenhum alerta no radar.</div><div v-for="j in jovens.filter(x=>x.status!=='Ativo')" :key="j.id" class="person"><div class="avatar soft">{{ iniciais(j.nome) }}</div><div><strong>{{ j.nome }}</strong><small>{{ j.equipe||'Sem equipe' }} · {{ j.tipo||'Participante' }}</small></div><span :class="['status',statusClasse(j.status)]">{{ j.status }}</span></div></article><article class="panel"><div class="panelhead"><div><small>AGENDA</small><h3>Próximos eventos</h3></div></div><div v-if="!eventos.length" class="quiet">Nenhum evento cadastrado.</div><div v-for="e in eventos.slice(0,4)" :key="e.id" class="event"><div class="date"><strong>{{ e.data.slice(8,10) }}</strong><small>{{ new Date(e.data+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','') }}</small></div><div><strong>{{ e.titulo }}</strong><small>{{ e.local||'Local a definir' }} · {{ e.inscritos }} inscritos</small></div></div></article></div>
        <article class="panel"><div class="summary"><div><strong>{{ menores }}</strong><small>menores de idade</small></div><div><strong>{{ jovens.length-menores }}</strong><small>maiores de idade</small></div><div><strong>{{ jovens.filter(j=>j.equipe).length }}</strong><small>em equipes</small></div><div><strong>{{ aniversariantesMes.length }}</strong><small>aniversários no mês</small></div></div></article>
      </section>

      <section v-else-if="tela==='jovens'" class="page">
        <div class="splithead"><p class="muted">Cadastro central local de participantes, visitantes e lideranças.</p><label>Buscar <input class="search" v-model="busca" placeholder="Nome, telefone, e-mail ou equipe"></label></div>
        <form class="formcard formgrid" @submit.prevent="adicionarJovem"><label>Nome completo *<input v-model="novo.nome" required></label><label>Telefone<input v-model="novo.telefone" inputmode="tel"></label><label>E-mail<input v-model="novo.email" type="email"></label><label>Data de nascimento<input v-model="novo.nascimento" type="date"></label><label>Perfil<select v-model="novo.tipo"><option>Participante</option><option>Visitante</option><option>Liderança</option></select></label><label>Equipe<select v-model="novo.equipe"><option value="">Sem equipe</option><option v-for="g in grupos.filter(x=>x.ativo)" :key="g.id" :value="g.nome">{{ g.nome }}</option></select></label><template v-if="novoMenor"><label>Responsável legal *<input v-model="novo.responsavel" required></label><label>Telefone do responsável *<input v-model="novo.telefoneResponsavel" inputmode="tel" required></label></template><button class="primary">Adicionar jovem</button></form>
        <article class="panel tablewrap"><table><thead><tr><th>Jovem</th><th>Contato</th><th>Equipe</th><th>Perfil</th><th>Status</th></tr></thead><tbody><tr v-for="j in filtrados" :key="j.id"><td><strong>{{ j.nome }}</strong><small>{{ j.nascimento||'Nascimento não informado' }}<template v-if="j.menor"> · Resp.: {{ j.responsavel||'não informado' }}</template></small></td><td>{{ j.telefone||'—' }}<small>{{ j.email||(j.menor?j.telefoneResponsavel:'')||'—' }}</small></td><td>{{ j.equipe||'Sem equipe' }}</td><td>{{ j.tipo||'Participante' }}<small>{{ j.menor?'Menor':'Adulto' }}</small></td><td><select class="statusselect" v-model="j.status" :aria-label="`Status de ${j.nome}`"><option>Ativo</option><option>Atenção</option><option>Acompanhamento</option></select></td></tr></tbody></table></article>
      </section>

      <section v-else-if="tela==='eventos'" class="page"><p class="muted">Encontros, formações, retiros, viagens e demais atividades.</p><form class="formcard" @submit.prevent="adicionarEvento"><label>Nome do evento *<input v-model="novoEvento.titulo" required></label><label>Data *<input v-model="novoEvento.data" type="date" required></label><label>Local<input v-model="novoEvento.local"></label><button class="primary">Criar evento</button></form><div class="cards"><article class="panel" v-for="e in eventos" :key="e.id"><span class="eyebrow">{{ new Date(e.data+'T12:00:00').toLocaleDateString('pt-BR') }}</span><h3>{{ e.titulo }}</h3><p>{{ e.local||'Local a definir' }}</p><div class="cardfoot"><span><strong>{{ e.inscritos }}</strong> inscritos</span><div class="stepper"><button :aria-label="`Remover inscrito de ${e.titulo}`" @click="alterarInscritos(e.id,-1)">−</button><button :aria-label="`Adicionar inscrito em ${e.titulo}`" @click="alterarInscritos(e.id,1)">+</button></div></div></article></div></section>

      <section v-else-if="tela==='presenca'" class="page"><div class="hero compact"><div><span class="eyebrow">CHECK-IN · {{ new Date().toLocaleDateString('pt-BR') }}</span><h2>Presença do encontro</h2><p>As marcações são gravadas no cofre local criptografado.</p></div><div class="heroactions"><div class="bigcount">{{ presentesHoje }}/{{ jovens.length }}</div><button class="ghost" @click="marcarTodosPresentes">Marcar todos</button></div></div><article class="panel"><div v-for="j in jovens" :key="j.id" class="checkrow"><div class="avatar soft">{{ iniciais(j.nome) }}</div><div class="grow"><strong>{{ j.nome }}</strong><small>{{ j.equipe||'Sem equipe' }}</small></div><button :class="['presence',presente(j.id)?'yes':'']" @click="alternarPresenca(j.id)">{{ presente(j.id)?'✓ Presente':'Marcar presença' }}</button></div></article></section>

      <section v-else-if="tela==='grupos'" class="page"><div class="splithead"><p class="muted">Equipes, ministérios e pequenos grupos.</p><span class="badge">{{ grupos.filter(g=>g.ativo).length }} ativos</span></div><form class="formcard" @submit.prevent="adicionarGrupo"><label>Nome *<input v-model="novoGrupo.nome" required></label><label>Tipo<select v-model="novoGrupo.tipo"><option>Equipe</option><option>Grupo</option><option>Ministério</option></select></label><label>Líder<input v-model="novoGrupo.lider"></label><button class="primary">Criar</button></form><div class="cards"><article class="panel" v-for="g in distribuicaoEquipes" :key="g.id"><span class="eyebrow">{{ g.tipo.toUpperCase() }}</span><h3>{{ g.nome }}</h3><p>Liderança: <strong>{{ g.lider||'não definida' }}</strong></p><div class="cardfoot"><span>{{ g.membros }} integrantes</span><button class="link" @click="desativarGrupo(g.id)">Desativar</button></div></article></div></section>

      <section v-else-if="tela==='acompanhamento'" class="page"><div class="splithead"><p class="muted">Registre contatos e tarefas de cuidado.</p><span class="badge">{{ pendentes }} pendentes</span></div><form class="formcard formgrid" @submit.prevent="adicionarAcompanhamento"><label>Jovem *<select v-model="novoAcompanhamento.jovemId" required><option value="">Selecione</option><option v-for="j in jovens" :key="j.id" :value="j.id">{{ j.nome }}</option></select></label><label>Motivo / próxima ação *<input v-model="novoAcompanhamento.motivo" required></label><label>Responsável<input v-model="novoAcompanhamento.responsavel"></label><label>Prazo<input v-model="novoAcompanhamento.prazo" type="date"></label><button class="primary">Registrar</button></form><article class="panel tablewrap"><table><thead><tr><th>Jovem</th><th>Motivo</th><th>Responsável</th><th>Prazo</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="a in acompanhamentos" :key="a.id"><td><strong>{{ nomeJovem(a.jovemId) }}</strong><small>Criado em {{ new Date(a.criadoEm+'T12:00:00').toLocaleDateString('pt-BR') }}</small></td><td>{{ a.motivo }}</td><td>{{ a.responsavel||'—' }}</td><td>{{ a.prazo?new Date(a.prazo+'T12:00:00').toLocaleDateString('pt-BR'):'—' }}</td><td><span :class="['status',a.status==='Concluído'?'green':'yellow']">{{ a.status }}</span></td><td><button v-if="a.status==='Pendente'" class="link" @click="concluirAcompanhamento(a.id)">Concluir</button></td></tr></tbody></table></article></section>

      <section v-else-if="tela==='relatorios'" class="page"><div class="reportgrid"><article class="panel reportcard"><small>PRESENÇA REGISTRADA</small><strong>{{ taxaPresenca }}%</strong><p>Calculada somente sobre marcações efetivamente registradas em {{ diasComPresenca }} dia(s).</p></article><article class="panel reportcard"><small>INTEGRAÇÃO</small><strong>{{ visitantes }}</strong><p>Visitantes cadastrados.</p></article><article class="panel reportcard"><small>PROTEÇÃO</small><strong>{{ menores }}</strong><p>Menores identificados automaticamente pela data de nascimento.</p></article><article class="panel reportcard"><small>FOLLOW-UP</small><strong>{{ pendentes }}</strong><p>Tarefas em aberto.</p></article></div><div class="grid2"><article class="panel"><div class="panelhead"><h3>Jovens por equipe</h3></div><div v-for="g in distribuicaoEquipes" :key="g.id" class="barrow"><span>{{ g.nome }}</span><div class="bar"><i :style="{width:jovens.length?Math.max(4,g.membros/jovens.length*100)+'%':'0%'}"></i></div><strong>{{ g.membros }}</strong></div></article><article class="panel"><div class="panelhead"><h3>Aniversários no mês</h3></div><div v-if="!aniversariantesMes.length" class="quiet">Nenhum aniversário neste mês.</div><div v-for="j in aniversariantesMes" :key="j.id" class="person"><div class="avatar soft">{{ j.nascimento.slice(8,10) }}</div><div><strong>{{ j.nome }}</strong><small>{{ new Date(j.nascimento+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'long'}) }}</small></div></div></article></div></section>

      <section v-else-if="tela==='admin'" class="page"><div class="admin-grid"><article class="panel"><div class="panelhead"><h3>Configuração</h3></div><div class="stack"><label>Nome do grupo<input v-model="configuracao.nomeGrupo"></label><label>Cidade<input v-model="configuracao.cidade"></label><div class="twocol"><label>Alerta amarelo (dias)<input v-model.number="configuracao.radarAmarelo" type="number" min="1"></label><label>Alerta vermelho (dias)<input v-model.number="configuracao.radarVermelho" type="number" :min="configuracao.radarAmarelo"></label></div><button class="secondary" @click="recalcularRadar">Aplicar regras</button></div></article><article class="panel"><div class="panelhead"><h3>Backup criptografado</h3></div><p class="muted">O backup é cifrado com AES-GCM e a senha não é gravada.</p><div class="stack"><label>Senha do backup<input v-model="senhaBackup" type="password" minlength="8" autocomplete="new-password"></label><div class="actions"><button class="primary" @click="exportarBackup">Exportar</button><label class="filebtn">Importar<input type="file" accept="application/json,.json" @change="importarBackup"></label></div></div></article></div><article class="panel"><div class="panelhead"><div><small>PERFIS LOCAIS</small><h3>Usuários planejados</h3></div><span class="badge">{{ usuarios.filter(u=>u.ativo).length }} ativos</span></div><form class="inlineform" @submit.prevent="adicionarUsuario"><label>Nome<input v-model="novoUsuario.nome" required></label><label>Perfil<select v-model="novoUsuario.perfil"><option>Administrador Master</option><option>Coordenação</option><option>Liderança</option><option>Comunicação</option><option>Financeiro</option><option>Consulta</option></select></label><button class="primary">Adicionar</button></form><div class="userlist"><div v-for="u in usuarios" :key="u.id" class="person"><div class="avatar soft">{{ iniciais(u.nome) }}</div><div><strong>{{ u.nome }}</strong><small>{{ u.perfil }}</small></div><label class="switchlabel"><input type="checkbox" v-model="u.ativo"> {{ u.ativo?'Ativo':'Inativo' }}</label></div></div><div class="notice">Estes perfis ainda não equivalem a autenticação/RBAC central. O cofre protege o dispositivo; o backend multiusuário será a camada de autorização entre contas.</div></article></section>
    </main>
  </div>
</template>
